### ISSUE TITLE
smart contract audit issues

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/atomic-assets-contract#10]
fix smart contract audit issues identified by warp:
 * state assignments in constructor 
 * validate function setting missing required state variables if they are not set during deploy
 * run basic tests

**Comment by l-silvestre** [comment]
blocked while waiting for warp to finish audit and whitelist contract

**Comment by l-silvestre** [comment]
new feedback:
* remove constructor if not to be used
* remove number checks to ```isNan(parseInt(qty))```
* prune claims array after x days (check with block) so it does not get too big (degrading performance reading state)
